### ISSUE TITLE
Changelog ?

### ISSUE THREAD

**Issue by BloodofJesus** [metalcanine/Cube2.1#1]
Hi, I cant find any information about what has been changed/updated ?

**Comment by metalcanine** [comment]
Hi! I honestly haven't changed much in this repo yet.
All of what has been done so far are small API call changes from SDL 1.2 to SDL 2.0 and can be found in the `sdl` branch, but this repo is currently in a broken state.
For a working and more complete SDL2 conversion of the Cube2 engine extra-a has [sauer-cube](https://github.com/extra-a/sauer-sdl2)

Hope that this helps 💛

**Comment by BloodofJesus** [comment]
Thanks, his version is acctually the same I've been using. 
I'm not sure how :yellow_heart:  helps but okay :smile:
